trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:

# =========================
# Install Node.js
# =========================
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

# =========================
# Build Angular Frontend
# =========================
- script: |
    cd frontend/wms-frontend
    npm install
    npm run build
  displayName: 'Build Angular Frontend'

# =========================
# Install .NET SDK
# =========================
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.0.x'
  displayName: 'Install .NET SDK'

# =========================
# Restore Backend Dependencies
# =========================
- script: |
    cd backend
    dotnet restore
  displayName: 'Restore .NET Dependencies'

# =========================
# Build Backend
# =========================
- script: |
    cd backend
    dotnet build --configuration $(buildConfiguration)
  displayName: 'Build .NET Backend'
